webtalk_init -webtalk_dir C:/Users/julix/git/DDCA/lab_9/Lab9_student/lab_9.sim/sim_1/behav/xsim/xsim.dir/MIPS_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jun  4 08:44:02 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "838d40b2-725a-44df-8306-a6b2a4eb3832" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7e17bd2c72234a3a8aac19d19ed497ee" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "51" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-8350 Eight-Core Processor           " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4019 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "20" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "133 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "109 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "3682" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "542" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "3.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "81240_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1651625103 -regid "" -xml C:/Users/julix/git/DDCA/lab_9/Lab9_student/lab_9.sim/sim_1/behav/xsim/xsim.dir/MIPS_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/julix/git/DDCA/lab_9/Lab9_student/lab_9.sim/sim_1/behav/xsim/xsim.dir/MIPS_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/julix/git/DDCA/lab_9/Lab9_student/lab_9.sim/sim_1/behav/xsim/xsim.dir/MIPS_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
